local ruin = {name = "Destroyed Fort"}
local direct = defines.direction

ruin.entities = {
    {name = "gate", position = {-1.0, 4.0}, direction = direct.east},
    {name = "gate", position = {0.0, 4.0}, direction = direct.east},
    {name = "gate", position = {2.0, 4.0}, direction = direct.east},
    {name = "gun-turret", position = {-7.5, 2.5}},
    {name = "gun-turret", position = {7.5, 2.5}},
    {name = "medium-electric-pole", position = {-7.0, -1.0}},
    {name = "medium-electric-pole", position = {2.0, 1.0}},
    {name = "radar", position = {-1.0, -1.0}},
    {name = "radar", position = {2.0, -1.0}},
    {name = "radar", position = {5.0, -1.0}},
    {name = "stone-wall", position = {-9.0, -5.0}},
    {name = "stone-wall", position = {-9.0, -4.0}},
    {name = "stone-wall", position = {-9.0, -3.0}},
    {name = "stone-wall", position = {-9.0, -2.0}},
    {name = "stone-wall", position = {-9.0, 0.0}},
    {name = "stone-wall", position = {-9.0, 1.0}},
    {name = "stone-wall", position = {-9.0, 2.0}},
    {name = "stone-wall", position = {-9.0, 3.0}},
    {name = "stone-wall", position = {-9.0, 4.0}},
    {name = "stone-wall", position = {-8.0, -5.0}},
    {name = "stone-wall", position = {-8.0, 4.0}},
    {name = "stone-wall", position = {-7.0, -5.0}},
    {name = "stone-wall", position = {-7.0, 4.0}},
    {name = "stone-wall", position = {-6.0, -5.0}},
    {name = "stone-wall", position = {-6.0, 4.0}},
    {name = "stone-wall", position = {-5.0, -5.0}},
    {name = "stone-wall", position = {-5.0, 4.0}},
    {name = "stone-wall", position = {-3.0, -5.0}},
    {name = "stone-wall", position = {-3.0, 4.0}},
    {name = "stone-wall", position = {-2.0, -5.0}},
    {name = "stone-wall", position = {-2.0, 4.0}},
    {name = "stone-wall", position = {-1.0, -5.0}},
    {name = "stone-wall", position = {1.0, -5.0}},
    {name = "stone-wall", position = {2.0, -5.0}},
    {name = "stone-wall", position = {3.0, -5.0}},
    {name = "stone-wall", position = {3.0, 4.0}},
    {name = "stone-wall", position = {4.0, 4.0}},
    {name = "stone-wall", position = {5.0, -5.0}},
    {name = "stone-wall", position = {5.0, 4.0}},
    {name = "stone-wall", position = {6.0, -5.0}},
    {name = "stone-wall", position = {7.0, -5.0}},
    {name = "stone-wall", position = {7.0, 4.0}},
    {name = "stone-wall", position = {8.0, -5.0}},
    {name = "stone-wall", position = {9.0, -4.0}},
    {name = "stone-wall", position = {9.0, -2.0}},
    {name = "stone-wall", position = {9.0, -1.0}},
    {name = "stone-wall", position = {8.0, 4.0}},
    {name = "stone-wall", position = {9.0, 0.0}},
    {name = "stone-wall", position = {9.0, 1.0}},
    {name = "stone-wall", position = {9.0, 3.0}},
    {name = "stone-wall", position = {9.0, 4.0}}
}

return ruin
