local ruin = {name="Destroyed Enemy Fort"}
local direct = defines.direction

ruin.entities = {
    {name = "assembling-machine-2", position = {-9.0, -5.0}},
    {name = "assembling-machine-2", position = {-8.0, -9.0}},
    {name = "assembling-machine-2", position = {-6.0, -5.0}},
    {name = "assembling-machine-2", position = {-4.0, -9.0}},
    {name = "assembling-machine-2", position = {-3.0, -5.0}},
    {name = "fast-inserter", position = {-13.0, -11.0}, direction = direct.south},
    {name = "fast-inserter", position = {-12.0, 11.0}, direction = direct.south},
    {name = "fast-inserter", position = {-11.0, -13.0}, direction = direct.west},
    {name = "fast-inserter", position = {-9.0, -11.0}, direction = direct.north},
    {name = "fast-inserter", position = {-8.0, -7.0}, direction = direct.north},
    {name = "fast-inserter", position = {-8.0, -3.0}, direction = direct.north},
    {name = "fast-inserter", position = {-7.0, -7.0}, direction = direct.north},
    {name = "fast-inserter", position = {-7.0, -3.0}, direction = direct.north},
    {name = "fast-inserter", position = {-5.0, -7.0}, direction = direct.north},
    {name = "fast-inserter", position = {-5.0, -3.0}, direction = direct.north},
    {name = "fast-inserter", position = {-4.0, -11.0}, direction = direct.north},
    {name = "fast-inserter", position = {-4.0, -7.0}, direction = direct.north},
    {name = "fast-inserter", position = {-4.0, -3.0}, direction = direct.north},
    {name = "fast-inserter", position = {10.0, -13.0}, direction = direct.west},
    {name = "fast-inserter", position = {10.0, 13.0}, direction = direct.east},
    {name = "fast-inserter", position = {12.0, -11.0}, direction = direct.north},
    {name = "fast-inserter", position = {12.0, 11.0}, direction = direct.north},
    {name = "gun-turret", position = {-12.5, -12.5}},
    {name = "gun-turret", position = {-11.5, 12.5}},
    {name = "gun-turret", position = {11.5, -12.5}},
    {name = "gun-turret", position = {11.5, 12.5}},
    {name = "lab", position = {2.0, 4.0}},
    {name = "lab", position = {2.0, 7.0}},
    {name = "lab", position = {5.0, 7.0}},
    {name = "medium-electric-pole", position = {-6.0, -3.0}},
    {name = "medium-electric-pole", position = {-6.0, -7.0}},
    {name = "medium-electric-pole", position = {10.0, -11.0}},
    {name = "stone-wall", position = {-16.0, -16.0}},
    {name = "stone-wall", position = {-16.0, -15.0}},
    {name = "stone-wall", position = {-16.0, -14.0}},
    {name = "stone-wall", position = {-16.0, -11.0}},
    {name = "stone-wall", position = {-16.0, -10.0}},
    {name = "stone-wall", position = {-16.0, -9.0}},
    {name = "stone-wall", position = {-16.0, -6.0}},
    {name = "stone-wall", position = {-16.0, -5.0}},
    {name = "stone-wall", position = {-16.0, -4.0}},
    {name = "stone-wall", position = {-16.0, -3.0}},
    {name = "stone-wall", position = {-16.0, -2.0}},
    {name = "stone-wall", position = {-16.0, 0.0}},
    {name = "stone-wall", position = {-16.0, 1.0}},
    {name = "stone-wall", position = {-16.0, 2.0}},
    {name = "stone-wall", position = {-16.0, 3.0}},
    {name = "stone-wall", position = {-16.0, 7.0}},
    {name = "stone-wall", position = {-16.0, 8.0}},
    {name = "stone-wall", position = {-16.0, 9.0}},
    {name = "stone-wall", position = {-16.0, 13.0}},
    {name = "stone-wall", position = {-16.0, 14.0}},
    {name = "stone-wall", position = {-16.0, 15.0}},
    {name = "stone-wall", position = {-15.0, -16.0}},
    {name = "stone-wall", position = {-15.0, 15.0}},
    {name = "stone-wall", position = {-14.0, 15.0}},
    {name = "stone-wall", position = {-13.0, -16.0}},
    {name = "stone-wall", position = {-13.0, 15.0}},
    {name = "stone-wall", position = {-11.0, 15.0}},
    {name = "stone-wall", position = {-10.0, -16.0}},
    {name = "stone-wall", position = {-10.0, 15.0}},
    {name = "stone-wall", position = {-9.0, -16.0}},
    {name = "stone-wall", position = {-9.0, 15.0}},
    {name = "stone-wall", position = {-8.0, -16.0}},
    {name = "stone-wall", position = {-7.0, 15.0}},
    {name = "stone-wall", position = {-6.0, -16.0}},
    {name = "stone-wall", position = {-6.0, 15.0}},
    {name = "stone-wall", position = {-5.0, 15.0}},
    {name = "stone-wall", position = {-4.0, -16.0}},
    {name = "stone-wall", position = {-4.0, 15.0}},
    {name = "stone-wall", position = {-3.0, -16.0}},
    {name = "stone-wall", position = {-2.0, -16.0}},
    {name = "stone-wall", position = {-2.0, 15.0}},
    {name = "stone-wall", position = {-1.0, -16.0}},
    {name = "stone-wall", position = {-1.0, 15.0}},
    {name = "stone-wall", position = {0.0, -16.0}},
    {name = "stone-wall", position = {1.0, -16.0}},
    {name = "stone-wall", position = {2.0, -16.0}},
    {name = "stone-wall", position = {3.0, 15.0}},
    {name = "stone-wall", position = {5.0, 15.0}},
    {name = "stone-wall", position = {6.0, 15.0}},
    {name = "stone-wall", position = {7.0, 15.0}},
    {name = "stone-wall", position = {8.0, -16.0}},
    {name = "stone-wall", position = {9.0, -16.0}},
    {name = "stone-wall", position = {9.0, 15.0}},
    {name = "stone-wall", position = {10.0, 15.0}},
    {name = "stone-wall", position = {11.0, -16.0}},
    {name = "stone-wall", position = {11.0, 15.0}},
    {name = "stone-wall", position = {13.0, -16.0}},
    {name = "stone-wall", position = {14.0, -16.0}},
    {name = "stone-wall", position = {14.0, 15.0}},
    {name = "stone-wall", position = {15.0, -16.0}},
    {name = "stone-wall", position = {15.0, -15.0}},
    {name = "stone-wall", position = {15.0, -14.0}},
    {name = "stone-wall", position = {15.0, -13.0}},
    {name = "stone-wall", position = {15.0, -12.0}},
    {name = "stone-wall", position = {15.0, -11.0}},
    {name = "stone-wall", position = {15.0, -9.0}},
    {name = "stone-wall", position = {15.0, -8.0}},
    {name = "stone-wall", position = {15.0, -6.0}},
    {name = "stone-wall", position = {15.0, -5.0}},
    {name = "stone-wall", position = {15.0, -2.0}},
    {name = "stone-wall", position = {15.0, -1.0}},
    {name = "stone-wall", position = {15.0, 0.0}},
    {name = "stone-wall", position = {15.0, 4.0}},
    {name = "stone-wall", position = {15.0, 5.0}},
    {name = "stone-wall", position = {15.0, 9.0}},
    {name = "stone-wall", position = {15.0, 11.0}},
    {name = "stone-wall", position = {15.0, 12.0}},
    {name = "stone-wall", position = {15.0, 14.0}},
    {name = "stone-wall", position = {15.0, 15.0}},
    {name = "transport-belt", position = {-13.0, -10.0}, direction = direct.north},
    {name = "transport-belt", position = {-13.0, -9.0}, direction = direct.north},
    {name = "transport-belt", position = {-13.0, -8.0}, direction = direct.north},
    {name = "transport-belt", position = {-13.0, -6.0}, direction = direct.north},
    {name = "transport-belt", position = {-13.0, -5.0}, direction = direct.north},
    {name = "transport-belt", position = {-13.0, -4.0}, direction = direct.north},
    {name = "transport-belt", position = {-13.0, -3.0}, direction = direct.north},
    {name = "transport-belt", position = {-13.0, -2.0}, direction = direct.north},
    {name = "transport-belt", position = {-13.0, -1.0}, direction = direct.north},
    {name = "transport-belt", position = {-13.0, 1.0}, direction = direct.north},
    {name = "transport-belt", position = {-13.0, 2.0}, direction = direct.north},
    {name = "transport-belt", position = {-13.0, 3.0}, direction = direct.north},
    {name = "transport-belt", position = {-13.0, 5.0}, direction = direct.north},
    {name = "transport-belt", position = {-13.0, 7.0}, direction = direct.north},
    {name = "transport-belt", position = {-13.0, 8.0}, direction = direct.north},
    {name = "transport-belt", position = {-13.0, 9.0}, direction = direct.north},
    {name = "transport-belt", position = {-13.0, 10.0}, direction = direct.north},
    {name = "transport-belt", position = {-12.0, 10.0}, direction = direct.west},
    {name = "underground-belt", position = {-11.0, -12.0}, direction = direct.west},
    {name = "transport-belt", position = {-10.0, -12.0}, direction = direct.east},
    {name = "transport-belt", position = {-10.0, -2.0}, direction = direct.east},
    {name = "transport-belt", position = {-9.0, -13.0}, direction = direct.east},
    {name = "transport-belt", position = {-9.0, -12.0}, direction = direct.east},
    {name = "transport-belt", position = {-9.0, -2.0}, direction = direct.east},
    {name = "transport-belt", position = {-8.0, -13.0}, direction = direct.east},
    {name = "transport-belt", position = {-8.0, -12.0}, direction = direct.east},
    {name = "transport-belt", position = {-8.0, -2.0}, direction = direct.east},
    {name = "transport-belt", position = {-8.0, 13.0}, direction = direct.west},
    {name = "transport-belt", position = {-7.0, -13.0}, direction = direct.east},
    {name = "transport-belt", position = {-7.0, 13.0}, direction = direct.west},
    {name = "transport-belt", position = {-7.0, -2.0}, direction = direct.east},
    {name = "transport-belt", position = {-6.0, -13.0}, direction = direct.east},
    {name = "transport-belt", position = {-6.0, -12.0}, direction = direct.east},
    {name = "transport-belt", position = {-6.0, 13.0}, direction = direct.west},
    {name = "transport-belt", position = {-6.0, -2.0}, direction = direct.east},
    {name = "transport-belt", position = {-5.0, -13.0}, direction = direct.east},
    {name = "transport-belt", position = {-5.0, -12.0}, direction = direct.east},
    {name = "transport-belt", position = {-5.0, -2.0}, direction = direct.east},
    {name = "transport-belt", position = {-5.0, 13.0}, direction = direct.west},
    {name = "transport-belt", position = {-4.0, -13.0}, direction = direct.east},
    {name = "transport-belt", position = {-4.0, -2.0}, direction = direct.east},
    {name = "transport-belt", position = {-4.0, 13.0}, direction = direct.west},
    {name = "transport-belt", position = {-3.0, -13.0}, direction = direct.east},
    {name = "transport-belt", position = {-3.0, -12.0}, direction = direct.east},
    {name = "transport-belt", position = {-3.0, -2.0}, direction = direct.east},
    {name = "transport-belt", position = {-3.0, 13.0}, direction = direct.west},
    {name = "transport-belt", position = {-2.0, -13.0}, direction = direct.east},
    {name = "transport-belt", position = {-2.0, -12.0}, direction = direct.east},
    {name = "transport-belt", position = {-2.0, -2.0}, direction = direct.east},
    {name = "transport-belt", position = {-2.0, 13.0}, direction = direct.west},
    {name = "transport-belt", position = {-1.0, 13.0}, direction = direct.west},
    {name = "transport-belt", position = {0.0, -13.0}, direction = direct.east},
    {name = "transport-belt", position = {0.0, 13.0}, direction = direct.west},
    {name = "transport-belt", position = {1.0, -13.0}, direction = direct.east},
    {name = "transport-belt", position = {2.0, -13.0}, direction = direct.east},
    {name = "transport-belt", position = {3.0, -13.0}, direction = direct.east},
    {name = "transport-belt", position = {4.0, 13.0}, direction = direct.west},
    {name = "transport-belt", position = {5.0, 13.0}, direction = direct.west},
    {name = "transport-belt", position = {6.0, 13.0}, direction = direct.west},
    {name = "transport-belt", position = {7.0, 13.0}, direction = direct.west},
    {name = "transport-belt", position = {8.0, -13.0}, direction = direct.east},
    {name = "transport-belt", position = {8.0, 13.0}, direction = direct.west},
    {name = "transport-belt", position = {9.0, -13.0}, direction = direct.east},
    {name = "transport-belt", position = {9.0, 13.0}, direction = direct.west},
    {name = "transport-belt", position = {12.0, -10.0}, direction = direct.south},
    {name = "transport-belt", position = {12.0, -9.0}, direction = direct.south},
    {name = "transport-belt", position = {12.0, -8.0}, direction = direct.south},
    {name = "transport-belt", position = {12.0, -7.0}, direction = direct.south},
    {name = "transport-belt", position = {12.0, -6.0}, direction = direct.south},
    {name = "transport-belt", position = {12.0, -5.0}, direction = direct.south},
    {name = "transport-belt", position = {12.0, -3.0}, direction = direct.south},
    {name = "transport-belt", position = {12.0, -2.0}, direction = direct.south},
    {name = "transport-belt", position = {12.0, 1.0}, direction = direct.south},
    {name = "transport-belt", position = {12.0, 2.0}, direction = direct.south},
    {name = "transport-belt", position = {12.0, 3.0}, direction = direct.south},
    {name = "transport-belt", position = {12.0, 4.0}, direction = direct.south},
    {name = "transport-belt", position = {12.0, 5.0}, direction = direct.south},
    {name = "transport-belt", position = {12.0, 7.0}, direction = direct.south},
    {name = "transport-belt", position = {12.0, 8.0}, direction = direct.south},
    {name = "transport-belt", position = {12.0, 10.0}, direction = direct.south}
}

return ruin
