local ruin = {name = "Early Game Setups"}
local direct = defines.direction

ruin.entities = {
    {name = "fast-inserter", position = {-5.0, -11.0}, direction = direct.west},
    {name = "fast-inserter", position = {-5.0, -7.0}, direction = direct.east},
    {name = "fast-inserter", position = {-3.0, 4.0}, direction = direct.west},
    {name = "fast-inserter", position = {-3.0, 6.0}, direction = direct.west},
    {name = "fast-inserter", position = {-3.0, 10.0}, direction = direct.west},
    {name = "fast-inserter", position = {-1.0, -9.0}, direction = direct.west},
    {name = "fast-inserter", position = {0.0, 2.0}, direction = direct.west},
    {name = "fast-inserter", position = {0.0, 4.0}, direction = direct.west},
    {name = "fast-inserter", position = {0.0, 8.0}, direction = direct.west},
    {name = "fast-inserter", position = {3.0, -11.0}, direction = direct.west},
    {name = "fast-inserter", position = {3.0, -5.0}, direction = direct.east},
    {name = "fast-inserter", position = {3.0, -7.0}, direction = direct.east},
    {name = "fast-inserter", position = {3.0, -9.0}, direction = direct.west},
    {name = "fast-inserter", position = {4.0, -8.0}, direction = direct.north},
    {name = "fast-inserter", position = {6.0, -8.0}, direction = direct.north},
    {name = "lab", position = {-7.0, -10.0}},
    {name = "lab", position = {-7.0, -6.0}},
    {name = "lab", position = {-3.0, -10.0}},
    {name = "lab", position = {-3.0, -6.0}},
    {name = "lab", position = {1.0, -10.0}},
    {name = "lab", position = {1.0, -6.0}},
    {name = "lab", position = {5.0, -6.0}},
    {name = "radar", position = {7.0, 0.0}},
    {name = "small-electric-pole", position = {-5.0, -10.0}},
    {name = "small-electric-pole", position = {-5.0, -6.0}},
    {name = "small-electric-pole", position = {-1.0, -6.0}},
    {name = "small-electric-pole", position = {3.0, -10.0}},
    {name = "small-electric-pole", position = {3.0, -6.0}},
    {name = "small-electric-pole", position = {5.0, -8.0}},
    {name = "stone-furnace", position = {-1.5, 1.5}},
    {name = "stone-furnace", position = {-1.5, 3.5}},
    {name = "stone-furnace", position = {-1.5, 5.5}},
    {name = "stone-furnace", position = {-1.5, 7.5}},
    {name = "stone-furnace", position = {-1.5, 9.5}},
    {name = "transport-belt", position = {-7.0, 2.0}, direction = direct.east},
    {name = "transport-belt", position = {-5.0, 2.0}, direction = direct.east},
    {name = "transport-belt", position = {-4.0, 2.0}, direction = direct.south},
    {name = "transport-belt", position = {-4.0, 3.0}, direction = direct.south},
    {name = "transport-belt", position = {-4.0, 4.0}, direction = direct.south},
    {name = "transport-belt", position = {-4.0, 6.0}, direction = direct.south},
    {name = "transport-belt", position = {-4.0, 7.0}, direction = direct.south},
    {name = "transport-belt", position = {-4.0, 8.0}, direction = direct.south},
    {name = "transport-belt", position = {-4.0, 10.0}, direction = direct.south},
    {name = "transport-belt", position = {1.0, 3.0}, direction = direct.south},
    {name = "transport-belt", position = {1.0, 4.0}, direction = direct.south},
    {name = "transport-belt", position = {1.0, 5.0}, direction = direct.south},
    {name = "transport-belt", position = {1.0, 7.0}, direction = direct.south},
    {name = "transport-belt", position = {1.0, 8.0}, direction = direct.south},
    {name = "transport-belt", position = {1.0, 9.0}, direction = direct.south}
}

return ruin
