local ruin = {name = "Overgrown Fort"}
local direct = defines.direction

ruin.entities = {
    {name = "gate", position = {-6.0, 0.0}, direction = direct.north},
    {name = "gate", position = {-6.0, 1.0}, direction = direct.north},
    {name = "gate", position = {-2.0, 6.0}, direction = direct.east},
    {name = "gate", position = {0.0, -6.0}, direction = direct.east},
    {name = "gate", position = {1.0, -6.0}, direction = direct.east},
    {name = "gate", position = {6.0, -1.0}, direction = direct.north},
    {name = "gate", position = {6.0, 0.0}, direction = direct.north},
    {name = "gun-turret", position = {1.5, 1.5}},
    {name = "randomTree", position = {-5.5, -4.5}},
    {name = "randomTree", position = {-4.5, 2.5}},
    {name = "randomTree", position = {-1.5, 1.5}},
    {name = "randomTree", position = {-0.5, -3.5}},
    {name = "randomTree", position = {-0.5, 4.5}},
    {name = "randomTree", position = {2.5, -0.5}},
    {name = "randomTree", position = {4.5, -1.5}},
    {name = "randomTree", position = {4.5, 2.5}},
    {name = "randomTree", position = {5.5, -6.5}},
    {name = "stone-wall", position = {-6.0, -6.0}},
    {name = "stone-wall", position = {-6.0, -3.0}},
    {name = "stone-wall", position = {-6.0, -2.0}},
    {name = "stone-wall", position = {-6.0, -1.0}},
    {name = "stone-wall", position = {-6.0, 2.0}},
    {name = "stone-wall", position = {-6.0, 3.0}},
    {name = "stone-wall", position = {-6.0, 4.0}},
    {name = "stone-wall", position = {-6.0, 5.0}},
    {name = "stone-wall", position = {-5.0, -6.0}},
    {name = "stone-wall", position = {-5.0, -2.0}},
    {name = "stone-wall", position = {-5.0, 6.0}},
    {name = "stone-wall", position = {-4.0, -6.0}},
    {name = "stone-wall", position = {-4.0, -4.0}},
    {name = "stone-wall", position = {-4.0, 6.0}},
    {name = "stone-wall", position = {-3.0, -4.0}},
    {name = "stone-wall", position = {-3.0, 6.0}},
    {name = "stone-wall", position = {-2.0, -6.0}},
    {name = "stone-wall", position = {-2.0, -2.0}},
    {name = "stone-wall", position = {-1.0, -6.0}},
    {name = "stone-wall", position = {-1.0, 0.0}},
    {name = "stone-wall", position = {0.0, 0.0}},
    {name = "stone-wall", position = {0.0, 1.0}},
    {name = "stone-wall", position = {0.0, 2.0}},
    {name = "stone-wall", position = {0.0, 6.0}},
    {name = "stone-wall", position = {1.0, -1.0}},
    {name = "stone-wall", position = {1.0, 0.0}},
    {name = "stone-wall", position = {1.0, 6.0}},
    {name = "stone-wall", position = {2.0, -6.0}},
    {name = "stone-wall", position = {2.0, -4.0}},
    {name = "stone-wall", position = {2.0, 3.0}},
    {name = "stone-wall", position = {2.0, 5.0}},
    {name = "stone-wall", position = {2.0, 6.0}},
    {name = "stone-wall", position = {3.0, -6.0}},
    {name = "stone-wall", position = {3.0, -4.0}},
    {name = "stone-wall", position = {3.0, 6.0}},
    {name = "stone-wall", position = {4.0, -6.0}},
    {name = "stone-wall", position = {4.0, -4.0}},
    {name = "stone-wall", position = {4.0, -3.0}},
    {name = "stone-wall", position = {5.0, 6.0}},
    {name = "stone-wall", position = {6.0, -5.0}},
    {name = "stone-wall", position = {6.0, -3.0}},
    {name = "stone-wall", position = {6.0, -2.0}},
    {name = "stone-wall", position = {6.0, 1.0}},
    {name = "stone-wall", position = {6.0, 2.0}},
    {name = "stone-wall", position = {6.0, 3.0}},
    {name = "stone-wall", position = {6.0, 5.0}},
    {name = "stone-wall", position = {6.0, 6.0}},
    {name = "wooden-chest", position = {0.0, -1.0}}
}

return ruin
