local ruin = {name = "Rough Fort"}
local direct = defines.direction

ruin.entities = {
    {name = "gate", position = {6.0, 4.0}, direction = direct.north},
    {name = "gate", position = {6.0, 5.0}, direction = direct.north},
    {name = "gun-turret", position = {-2.5, 4.5}},
    {name = "gun-turret", position = {2.5, -2.5}},
    {name = "land-mine", position = {4.86328125, 4.16796875}},
    {name = "medium-electric-pole", position = {-4.0, -4.0}},
    {name = "medium-electric-pole", position = {1.0, 2.0}},
    {name = "radar", position = {-1.0, -1.0}},
    {name = "radar", position = {-1.0, 2.0}},
    {name = "randomTree", position = {-5.5, -4.5}},
    {name = "randomTree", position = {-5.5, -2.5}},
    {name = "randomTree", position = {-5.5, 3.5}},
    {name = "randomTree", position = {-5.5, 5.5}},
    {name = "randomTree", position = {-2.5, -5.5}},
    {name = "randomTree", position = {-1.5, 6.5}},
    {name = "randomTree", position = {-0.5, -5.5}},
    {name = "randomTree", position = {1.5, 6.5}},
    {name = "randomTree", position = {2.5, -5.5}},
    {name = "randomTree", position = {4.5, 6.5}},
    {name = "randomTree", position = {5.5, -5.5}},
    {name = "randomTree", position = {5.5, -3.5}},
    {name = "randomTree", position = {5.5, -0.5}},
    {name = "randomTree", position = {5.5, 2.5}},
    {name = "stone-wall", position = {-6.0, -6.0}},
    {name = "stone-wall", position = {-6.0, -1.0}},
    {name = "stone-wall", position = {-6.0, 0.0}},
    {name = "stone-wall", position = {-6.0, 1.0}},
    {name = "stone-wall", position = {-6.0, 2.0}},
    {name = "stone-wall", position = {-6.0, 7.0}},
    {name = "stone-wall", position = {-5.0, -6.0}},
    {name = "stone-wall", position = {-5.0, 7.0}},
    {name = "stone-wall", position = {-4.0, -6.0}},
    {name = "stone-wall", position = {-4.0, 7.0}},
    {name = "stone-wall", position = {-3.0, 7.0}},
    {name = "stone-wall", position = {0.0, 7.0}},
    {name = "stone-wall", position = {1.0, -6.0}},
    {name = "stone-wall", position = {3.0, 7.0}},
    {name = "stone-wall", position = {4.0, -6.0}},
    {name = "stone-wall", position = {6.0, -2.0}},
    {name = "stone-wall", position = {6.0, 1.0}},
    {name = "stone-wall", position = {6.0, 6.0}},
    {name = "stone-wall", position = {6.0, 7.0}}
}

return ruin
