local ruin = {name = "Storage Area"}
local direct = defines.direction

ruin.entities = {
    {name = "gate", position = {-7.0, -1.0}, direction = direct.north},
    {name = "gate", position = {-7.0, 0.0}, direction = direct.north},
    {name = "gate", position = {-2.0, -6.0}, direction = direct.east},
    {name = "gate", position = {-1.0, -6.0}, direction = direct.east},
    {name = "gate", position = {-1.0, 6.0}, direction = direct.east},
    {name = "gate", position = {0.0, 6.0}, direction = direct.east},
    {name = "gate", position = {5.0, -1.0}, direction = direct.north},
    {name = "gate", position = {5.0, -2.0}, direction = direct.north},
    {name = "iron-chest", position = {-6.0, -1.0}},
    {name = "iron-chest", position = {-4.0, 4.0}},
    {name = "iron-chest", position = {-3.0, 1.0}},
    {name = "iron-chest", position = {-1.0, -3.0}},
    {name = "iron-chest", position = {-1.0, 4.0}},
    {name = "iron-chest", position = {2.0, 4.0}},
    {name = "iron-chest", position = {3.0, -2.0}},
    {name = "iron-chest", position = {3.0, -3.0}},
    {name = "iron-chest", position = {3.0, 0.0}},
    {name = "stone-wall", position = {-7.0, -2.0}},
    {name = "stone-wall", position = {-7.0, -3.0}},
    {name = "stone-wall", position = {-7.0, -4.0}},
    {name = "stone-wall", position = {-7.0, -5.0}},
    {name = "stone-wall", position = {-7.0, -6.0}},
    {name = "stone-wall", position = {-7.0, 1.0}},
    {name = "stone-wall", position = {-7.0, 2.0}},
    {name = "stone-wall", position = {-7.0, 3.0}},
    {name = "stone-wall", position = {-7.0, 4.0}},
    {name = "stone-wall", position = {-7.0, 5.0}},
    {name = "stone-wall", position = {-7.0, 6.0}},
    {name = "stone-wall", position = {-6.0, -6.0}},
    {name = "stone-wall", position = {-6.0, 6.0}},
    {name = "stone-wall", position = {-5.0, -6.0}},
    {name = "stone-wall", position = {-5.0, 6.0}},
    {name = "stone-wall", position = {-4.0, -6.0}},
    {name = "stone-wall", position = {-4.0, 6.0}},
    {name = "stone-wall", position = {-3.0, -6.0}},
    {name = "stone-wall", position = {-3.0, 6.0}},
    {name = "stone-wall", position = {-2.0, 6.0}},
    {name = "stone-wall", position = {0.0, -6.0}},
    {name = "stone-wall", position = {1.0, -6.0}},
    {name = "stone-wall", position = {1.0, 6.0}},
    {name = "stone-wall", position = {2.0, -6.0}},
    {name = "stone-wall", position = {2.0, 6.0}},
    {name = "stone-wall", position = {3.0, -6.0}},
    {name = "stone-wall", position = {3.0, 6.0}},
    {name = "stone-wall", position = {4.0, -6.0}},
    {name = "stone-wall", position = {4.0, 6.0}},
    {name = "stone-wall", position = {5.0, -3.0}},
    {name = "stone-wall", position = {5.0, -4.0}},
    {name = "stone-wall", position = {5.0, -5.0}},
    {name = "stone-wall", position = {5.0, -6.0}},
    {name = "stone-wall", position = {5.0, 0.0}},
    {name = "stone-wall", position = {5.0, 1.0}},
    {name = "stone-wall", position = {5.0, 2.0}},
    {name = "stone-wall", position = {5.0, 3.0}},
    {name = "stone-wall", position = {5.0, 4.0}},
    {name = "stone-wall", position = {5.0, 5.0}},
    {name = "stone-wall", position = {5.0, 6.0}},
    {name = "wooden-chest", position = {-6.0, -4.0}},
    {name = "wooden-chest", position = {-6.0, 2.0}},
    {name = "wooden-chest", position = {-6.0, 4.0}},
    {name = "wooden-chest", position = {-5.0, -4.0}},
    {name = "wooden-chest", position = {-5.0, 0.0}},
    {name = "wooden-chest", position = {-5.0, 2.0}},
    {name = "wooden-chest", position = {-4.0, -5.0}},
    {name = "wooden-chest", position = {-4.0, -2.0}},
    {name = "wooden-chest", position = {-4.0, 2.0}},
    {name = "wooden-chest", position = {-3.0, 0.0}},
    {name = "wooden-chest", position = {-3.0, 3.0}},
    {name = "wooden-chest", position = {-2.0, 3.0}},
    {name = "wooden-chest", position = {-1.0, -1.0}},
    {name = "wooden-chest", position = {0.0, -5.0}},
    {name = "wooden-chest", position = {0.0, 1.0}},
    {name = "wooden-chest", position = {1.0, -4.0}},
    {name = "wooden-chest", position = {1.0, -3.0}},
    {name = "wooden-chest", position = {1.0, 1.0}},
    {name = "wooden-chest", position = {1.0, 2.0}},
    {name = "wooden-chest", position = {2.0, -4.0}},
    {name = "wooden-chest", position = {3.0, 2.0}}
}

return ruin
