local ruin = {name = "Tree Island"}

ruin.entities = {
    {name = "randomTree", position = {-1.5, -2.5}},
    {name = "randomTree", position = {0.5, -2.5}}
}

ruin.tiles = {
    {name = "water", position = {-5.0, -5.0}},
    {name = "water", position = {-5.0, -4.0}},
    {name = "water", position = {-5.0, -3.0}},
    {name = "water", position = {-5.0, -2.0}},
    {name = "water", position = {-5.0, -1.0}},
    {name = "water", position = {-5.0, 0.0}},
    {name = "water", position = {-5.0, 1.0}},
    {name = "water", position = {-5.0, 2.0}},
    {name = "water", position = {-5.0, 3.0}},
    {name = "water", position = {-5.0, 4.0}},
    {name = "water", position = {-4.0, -5.0}},
    {name = "water", position = {-4.0, -4.0}},
    {name = "water", position = {-4.0, -3.0}},
    {name = "water", position = {-4.0, -2.0}},
    {name = "water", position = {-4.0, -1.0}},
    {name = "water", position = {-4.0, 0.0}},
    {name = "water", position = {-4.0, 1.0}},
    {name = "water", position = {-4.0, 2.0}},
    {name = "water", position = {-4.0, 3.0}},
    {name = "water", position = {-4.0, 4.0}},
    {name = "water", position = {-3.0, -5.0}},
    {name = "water", position = {-3.0, -4.0}},
    {name = "water", position = {-3.0, 0.0}},
    {name = "water", position = {-3.0, 1.0}},
    {name = "water", position = {-3.0, 2.0}},
    {name = "water", position = {-3.0, 3.0}},
    {name = "water", position = {-3.0, 4.0}},
    {name = "water", position = {-2.0, -5.0}},
    {name = "water", position = {-2.0, -4.0}},
    {name = "water", position = {-2.0, 0.0}},
    {name = "water", position = {-2.0, 1.0}},
    {name = "water", position = {-2.0, 2.0}},
    {name = "water", position = {-2.0, 3.0}},
    {name = "water", position = {-2.0, 4.0}},
    {name = "water", position = {-1.0, -5.0}},
    {name = "water", position = {-1.0, -4.0}},
    {name = "water", position = {0.0, -5.0}},
    {name = "water", position = {0.0, -4.0}},
    {name = "water", position = {1.0, -5.0}},
    {name = "water", position = {1.0, -4.0}},
    {name = "water", position = {1.0, 0.0}},
    {name = "water", position = {1.0, 1.0}},
    {name = "water", position = {1.0, 2.0}},
    {name = "water", position = {1.0, 3.0}},
    {name = "water", position = {1.0, 4.0}},
    {name = "water", position = {2.0, -5.0}},
    {name = "water", position = {2.0, -4.0}},
    {name = "water", position = {2.0, 0.0}},
    {name = "water", position = {2.0, 1.0}},
    {name = "water", position = {2.0, 2.0}},
    {name = "water", position = {2.0, 3.0}},
    {name = "water", position = {2.0, 4.0}},
    {name = "water", position = {3.0, -5.0}},
    {name = "water", position = {3.0, -4.0}},
    {name = "water", position = {3.0, -3.0}},
    {name = "water", position = {3.0, -2.0}},
    {name = "water", position = {3.0, -1.0}},
    {name = "water", position = {3.0, 0.0}},
    {name = "water", position = {3.0, 1.0}},
    {name = "water", position = {3.0, 2.0}},
    {name = "water", position = {3.0, 3.0}},
    {name = "water", position = {3.0, 4.0}},
    {name = "water", position = {4.0, -5.0}},
    {name = "water", position = {4.0, -4.0}},
    {name = "water", position = {4.0, -3.0}},
    {name = "water", position = {4.0, -2.0}},
    {name = "water", position = {4.0, -1.0}},
    {name = "water", position = {4.0, 0.0}},
    {name = "water", position = {4.0, 1.0}},
    {name = "water", position = {4.0, 2.0}},
    {name = "water", position = {4.0, 3.0}},
    {name = "water", position = {4.0, 4.0}},
}

return ruin
