local ruin = {name = "Tree Fort Trapped"}
local direct = defines.direction

ruin.entities = {
    {name = "gate", position = {-4.0, -6.0}, direction = direct.east},
    {name = "gate", position = {-1.0, 1.0}, direction = direct.east},
    {name = "gate", position = {1.0, 5.0}, direction = direct.east},
    {name = "gate", position = {5.0, 5.0}, direction = direct.east},
    {name = "land-mine", position = {-4.3359375, 2.50390625}},
    {name = "land-mine", position = {2.44921875, -1.72265625}},
    {name = "pipe-to-ground", position = {-1.0, -4.0}, direction = direct.south},
    {name = "pipe-to-ground", position = {-1.0, -3.0}, direction = direct.north},
    {name = "stone-wall", position = {-6.0, -6.0}},
    {name = "stone-wall", position = {-6.0, -5.0}},
    {name = "stone-wall", position = {-6.0, -4.0}},
    {name = "stone-wall", position = {-6.0, -3.0}},
    {name = "stone-wall", position = {-6.0, 0.0}},
    {name = "stone-wall", position = {-6.0, 1.0}},
    {name = "stone-wall", position = {-6.0, 2.0}},
    {name = "stone-wall", position = {-6.0, 3.0}},
    {name = "stone-wall", position = {-6.0, 4.0}},
    {name = "stone-wall", position = {-5.0, -6.0}},
    {name = "stone-wall", position = {-5.0, -3.0}},
    {name = "stone-wall", position = {-5.0, 1.0}},
    {name = "stone-wall", position = {-5.0, 5.0}},
    {name = "stone-wall", position = {-4.0, -3.0}},
    {name = "stone-wall", position = {-3.0, -6.0}},
    {name = "stone-wall", position = {-3.0, -3.0}},
    {name = "stone-wall", position = {-3.0, 1.0}},
    {name = "stone-wall", position = {-3.0, 5.0}},
    {name = "stone-wall", position = {-2.0, -6.0}},
    {name = "stone-wall", position = {-2.0, 0.0}},
    {name = "stone-wall", position = {-2.0, 1.0}},
    {name = "stone-wall", position = {-2.0, 5.0}},
    {name = "stone-wall", position = {-1.0, -6.0}},
    {name = "stone-wall", position = {-1.0, 5.0}},
    {name = "stone-wall", position = {0.0, -6.0}},
    {name = "stone-wall", position = {0.0, -3.0}},
    {name = "stone-wall", position = {0.0, 1.0}},
    {name = "stone-wall", position = {0.0, 2.0}},
    {name = "stone-wall", position = {0.0, 4.0}},
    {name = "stone-wall", position = {0.0, 5.0}},
    {name = "stone-wall", position = {1.0, -3.0}},
    {name = "stone-wall", position = {1.0, 1.0}},
    {name = "stone-wall", position = {2.0, -4.0}},
    {name = "stone-wall", position = {2.0, -3.0}},
    {name = "stone-wall", position = {2.0, 1.0}},
    {name = "stone-wall", position = {2.0, 5.0}},
    {name = "stone-wall", position = {3.0, -6.0}},
    {name = "stone-wall", position = {3.0, -3.0}},
    {name = "stone-wall", position = {3.0, 1.0}},
    {name = "stone-wall", position = {3.0, 5.0}},
    {name = "stone-wall", position = {4.0, -3.0}},
    {name = "stone-wall", position = {4.0, 0.0}},
    {name = "stone-wall", position = {4.0, 1.0}},
    {name = "stone-wall", position = {4.0, 2.0}},
    {name = "stone-wall", position = {4.0, 3.0}},
    {name = "stone-wall", position = {4.0, 4.0}},
    {name = "stone-wall", position = {4.0, 5.0}},
    {name = "stone-wall", position = {6.0, -6.0}},
    {name = "stone-wall", position = {6.0, -5.0}},
    {name = "stone-wall", position = {6.0, -2.0}},
    {name = "stone-wall", position = {6.0, -1.0}},
    {name = "stone-wall", position = {6.0, 0.0}},
    {name = "stone-wall", position = {6.0, 3.0}},
    {name = "stone-wall", position = {6.0, 4.0}},
    {name = "stone-wall", position = {6.0, 5.0}},
    {name = "randomTree", position = {-4.5, -4.5}},
    {name = "randomTree", position = {-1.5, -1.5}},
    {name = "randomTree", position = {2.5, 2.5}},
    {name = "randomTree", position = {4.5, -1.5}}
}

return ruin
